"""Compile production sensors.c; forbid all gauge writes during diagnostics."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
from host_build import sanitizer_flags
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
headers = {
    "freertos/FreeRTOS.h": """#pragma once
#include <stdbool.h>
#define pdTRUE 1
#define pdMS_TO_TICKS(x) (x)
""",
    "freertos/semphr.h": """#pragma once
typedef void *SemaphoreHandle_t;
typedef struct { int unused; } StaticSemaphore_t;
static inline void *xSemaphoreCreateMutexStatic(StaticSemaphore_t *s) { return s; }
static inline int xSemaphoreTake(void *s, unsigned ms) { (void)s; (void)ms; return 1; }
static inline int xSemaphoreGive(void *s) { (void)s; return 1; }
""",
    "esp_timer.h": """#pragma once
#include <stdint.h>
extern int64_t test_now_ms;
static inline int64_t esp_timer_get_time(void) { return test_now_ms*1000; }
""",
    "esp_err.h": """#pragma once
typedef int esp_err_t;
#define ESP_OK 0
#define ESP_FAIL -1
#define ESP_ERR_INVALID_STATE 259
#define ESP_ERR_INVALID_ARG 258
""",
    "esp_check.h": """#pragma once
#include "esp_err.h"
#define ESP_RETURN_ON_ERROR(expr,tag,...) do { int e=(expr); (void)(tag); if(e) return e; } while(0)
""",
    "esp_log.h": """#pragma once
#define ESP_LOGI(tag,...) ((void)(tag))
""",
    "driver/i2c_master.h": """#pragma once
#include <stdint.h>
#include <stddef.h>
#include "esp_err.h"
typedef void *i2c_master_dev_handle_t;
esp_err_t i2c_master_transmit_receive(i2c_master_dev_handle_t,const uint8_t*,size_t,uint8_t*,size_t,int);
esp_err_t i2c_master_transmit(i2c_master_dev_handle_t,const uint8_t*,size_t,int);
""",
}
harness = r'''
#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sensors.h"
int64_t test_now_ms;
static int stc_dev, cw_dev, reads, fail_reg=-1, fail_code=ESP_FAIL;
static uint8_t regs[19], ram[16], cwregs[11];
esp_err_t i2c_master_transmit(void *dev,const uint8_t *buf,size_t len,int timeout) {
    (void)dev; (void)buf; (void)len; (void)timeout;
    fputs("Diagnostics attempted a forbidden gauge write\n",stderr); abort();
}
esp_err_t i2c_master_transmit_receive(void *dev,const uint8_t *tx,size_t nt,uint8_t *rx,size_t nr,int timeout) {
    assert(nt==1 && timeout==100); ++reads;
    int reg=tx[0], key=(dev==&stc_dev ? 0x100 : 0x200)|reg;
    if (key==fail_reg) return fail_code;
    if(dev==&stc_dev) {
        if(reg==0) {assert(nr==sizeof(regs)); memcpy(rx,regs,nr);}
        else {assert(reg==0x20 && nr==sizeof(ram)); memcpy(rx,ram,nr);}
    } else {
        assert(dev==&cw_dev);
        assert((reg==2 && nr==2)||(reg==4 && nr==2)||(reg==10 && nr==1));
        memcpy(rx,cwregs+reg,nr);
    }
    return ESP_OK;
}
static void put16(int off,unsigned value) {regs[off]=value; regs[off+1]=value>>8;}
static int field(const char *record,const char *key) {
    char token[40]; snprintf(token,sizeof(token)," %s=",key);
    const char *p=strstr(record,token); assert(p); return atoi(p+strlen(token));
}
static void verify_record(char *out,size_t n) {
    assert(n==strlen(out) && n<320 && n>2 && !memcmp(out+n-2,"\r\n",2));
    assert(field(out,"v")==2);
}
int main(void) {
    sensors_init();
    char out[320];
    regs[0]=0x10; regs[1]=0x80; put16(2,75*512); put16(4,42);
    put16(6,0x3f00); put16(8,1800); put16(13,7200); put16(15,484); put16(17,344);
    /* Published official RAM/CRC vector, not generated by the function under test. */
    memcpy(ram,(uint8_t[]){0xa9,0x53,0x68,0x4e,0xe4,1,0x58,1,0x27,0,0x5d,0,0,0,0,0xbf},16);
    cwregs[2]=0x31; cwregs[3]=0x00; cwregs[4]=72;
    size_t n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out));
    verify_record(out,n); assert(reads==5);
    assert(field(out,"stc_err")==0 && field(out,"ctrl")==128 && field(out,"counter")==42);
    assert(field(out,"soc_raw")==38400 && field(out,"mv")==3960);
    assert(field(out,"current_raw")==0x3f00 && field(out,"ocv_raw")==7200);
    assert(field(out,"cc")==484 && field(out,"vm")==344);
    assert(field(out,"ram_ok")==1 && field(out,"seeded")==1 && field(out,"cw_soc")==72);
    /* A corrupt or missing shared seed marker must not look calibrated. */
    ram[10]^=1;
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(field(out,"ram_ok")==0 && field(out,"seeded")==0);
    memset(ram,0,sizeof(ram));
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(field(out,"ram_ok")==0 && field(out,"seeded")==0);
    fail_reg=0x120;
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(field(out,"ram_err")==ESP_FAIL && field(out,"ram_ok")==-1 && field(out,"seeded")==-1);
    /* Failed/MUX-unreachable reads are unknown, never an apparent empty battery. */
    fail_reg=0x100; fail_code=INT_MIN; reads=0;
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(reads==4 && field(out,"stc_err")==INT_MIN && field(out,"soc_raw")==-1 && field(out,"mv")==-1);
    fail_reg=0x204; fail_code=ESP_FAIL;
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(field(out,"cw_err")==ESP_FAIL && field(out,"cw_mv")==-1 && field(out,"cw_soc")==-1);
    fail_reg=-1; memset(regs,0xff,sizeof(regs)); memset(cwregs,0xff,sizeof(cwregs));
    n=sensors_format_diagnostics(&stc_dev,&cw_dev,out,sizeof(out)); verify_record(out,n);
    assert(field(out,"mv")==-2 && field(out,"soc_raw")==65535);
    reads=0; n=sensors_format_diagnostics(NULL,NULL,out,sizeof(out)); verify_record(out,n);
    assert(reads==0 && field(out,"stc_err")==ESP_ERR_INVALID_STATE && field(out,"cw_soc")==-1);
    assert(sensors_format_diagnostics(&stc_dev,&cw_dev,NULL,100)==0 && reads==0);
    assert(sensors_format_diagnostics(&stc_dev,&cw_dev,out,0)==0 && reads==0);
    char small[9]="garbage";
    assert(sensors_format_diagnostics(&stc_dev,&cw_dev,small,sizeof(small))==0 && small[0]=='\0');
    puts("sensors: read-only diagnostics, shared RAM CRC, signed voltage, bounded records, failed/MUX reads passed");
}
'''
def run_test(code, name):
    with tempfile.TemporaryDirectory(prefix="typix-sensors-test-") as directory:
        work = Path(directory)
        for header, content in headers.items():
            path = work / header
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        (work / "test.c").write_text(code)
        subprocess.run([
            "cc", "-std=c11", "-Wall", "-Wextra", "-Werror", *sanitizer_flags(),
            f"-I{work}", f"-I{root / 'main'}", str(root / "main/sensors.c"),
            str(root / "main/stc_gauge.c"), str(work / "test.c"), "-o", str(work / name),
        ], check=True)
        subprocess.run([str(work / name)], check=True)

if __name__ == "__main__":
    run_test(harness, "diagnostics")
    run_test((root / "tests/test_stc_gauge.c").read_text(), "gauge")
